name: Block Merge if Specific Label Not Added

on:
  pull_request_target:
    types: [labeled, synchronize, opened, reopened]

jobs:
  check-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI if not present
        run: |
          if ! command -v gh &> /dev/null; then
            echo "GitHub CLI not found. Installing..."
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
            sudo apt-add-repository https://cli.github.com/packages
            sudo apt-get update
            sudo apt-get install gh
          else
            echo "GitHub CLI is already installed."
          fi

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Verify Label Added
        id: check_label
        run: |
          LABEL_NAME="Approved"
          
          PR_NUMBER=$(jq --raw-output .number "$GITHUB_EVENT_PATH")
          LABELS=$(gh pr view $PR_NUMBER --json labels --jq '.labels[].name')
          LABEL_FOUND=false
          
          for LABEL in $LABELS; do
            if [[ "$LABEL" == "$LABEL_NAME" ]]; then
              LABEL_FOUND=true
              break
            fi
          done
          
          echo "LABEL_FOUND=$LABEL_FOUND" >> $GITHUB_ENV

      - name: Fail if Label Not Added
        if: env.LABEL_FOUND == 'false'
        run: |
          echo "The required label was not added. Blocking merge."
          exit 1
